Changed node version in packagejson to match nvmrc
MetaMask/metamask-module-template pull request #186
Opened 2023-04-19 16:01 UTC by BelfordZ

The nvmrc file specifies v16, the package.json#engines says greater than 14. This PR makes them both 16.

as an aside, using un-specific versions in nvmrc is discouraged. We should be specifying the exact version of node to be used.

2023-04-19 16:08 UTC, Gudahtt commented
Maybe better to title this as "Increase minimum supported Node.js version to v16".

The nvmrc and the minimum version are _intentionally_ out of sync in some projects, where a newer Node.js version provides a better development experience despite there being an intent to support older versions. But I agree it's simpler to keep them in sync.

2023-04-19 16:08 UTC, Gudahtt requested changes
Looks good except that the README also refers to v14. Could you update that as well?

2023-04-19 16:08 UTC, Gudahtt commented
>using un-specific versions in nvmrc is discouraged. We should be specifying the exact version of node to be used.

Could you elaborate on why this is discouraged?

2023-04-20 15:09 UTC, Gudahtt commented
I have created a new PR to handle this bump plus the v19 => v20 bump: https://github.com/MetaMask/metamask-module-template/pull/187

2023-04-20 19:25 UTC, BelfordZ commented
the purpose of nvmrc is to make sure we are all running the same node version. By specifying `v${NUMBER}`, its unclear what the actual node version will be. Further, the node version can change without the nvmrc file having changed.

Also if you use specific versions, you dont need to go figure out what v16 resolves to. 

nodenv doesn't support using unspecific versions like this, one of the reasons why it is a superior tool for this problem.

2023-04-20 19:29 UTC, closed without merging