ci: Run compatibility test ignoring lockfile
MetaMask/metamask-module-template pull request #215
Opened 2023-07-26 08:20 UTC by legobeat

This adds an additional run of tests against a state where `yarn.lock` is removed prior to the installation. This is intended to catch e.g. regressions and mislabeled breakage in updated transitive dependencies.

This will map more closely to what users get when installing the released package from registry.

Left out the intermediate versions of node as an optimization. The normal cache is still used since significant overlap is expected.

### Potential future improvements

- Run test against built package under another package manager (yarn v1 and/or npm)
  - Ensure there aren't implicit dependencies on yarn berry
  - Would allow throwing on breakages in `engines` without adding a plugin

2023-07-26 08:50 UTC, Mrtenz requested changes
Not sure I fully understand the need for this, but either way here's some nits. 😅

2023-07-26 08:50 UTC, Mrtenz commented on .github/workflows/build-lint-test.yml
> +  compat_test:
```suggestion

  compatibility-test:
```

2023-07-26 08:50 UTC, Mrtenz commented on .github/workflows/build-lint-test.yml
> +    name: Compatibility Test
```suggestion
    name: Compatibility test
```

2023-07-26 09:06 UTC, Mrtenz approved these changes
Makes sense!

2023-07-27 17:36 UTC, mcmire approved these changes
Looks good!

2023-07-31 15:57 UTC, merged