Add gh-action for npm publish on release create
MetaMask/metamask-module-template pull request #22
Opened 2020-09-24 22:56 UTC by danfinlay

Fixes #3

[Additional notes on configuration on team Roam](https://roamresearch.com/#/app/MetaMask/page/t4mYLgOZK)

2020-09-26 03:54 UTC, kumavis approved these changes

2020-09-26 04:45 UTC, rekmarks commented on .github/workflows/npm-publish.yaml
> +  build:
Is the this the name of the job? Should it be `build`?

2021-03-24 20:32 UTC, rekmarks requested changes
Pending discussion / further review, probably during tooling week.

2021-04-09 20:23 UTC, rekmarks commented
Discussion-to: #31

2021-06-30 03:29 UTC, rekmarks commented
After working with GitHub Actions since April, I've become convinced that safely setting up npm publishing in CI will require someone's dedicated time and attention, likely over the course of weeks. That someone will probably be our future tooling engineer. Until then, I will close this PR. We can use it as a point of reference, if necessary.

2021-06-30 03:29 UTC, closed without merging