Remove space from dependabot file name
MetaMask/metamask-module-template pull request #36
Opened 2021-04-05 17:34 UTC by darkwing

I noticed this file somehow had a space at the end.  🤔

2021-04-05 18:34 UTC, rekmarks requested changes
It's been renamed to `dependaboot`?

2021-04-05 18:47 UTC, darkwing commented
My Macbook's `o` key is broken, often double-o's me.  :(

2021-04-06 00:41 UTC, rekmarks approved these changes

2021-04-06 00:51 UTC, merged

2021-04-06 14:09 UTC, Gudahtt commented
Wow. I've never seen that happen before!